apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: slack-sink
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    name: github-events
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: slack-channel
