apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: slack-sink
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.source.github.issues
      repo: demo22
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: slack-broker
