apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: slack-sink
  annotations:
    kafka.eventing.knative.dev/delivery.order: ordered
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: slack-broker
