apiVersion: sources.knative.dev/v1alpha1
kind: GitHubSource
metadata:
  name: slack-persisted
spec:
  eventTypes:
    - issues
    - issue_comment
  ownerAndRepository: knativecon/demo22
  accessToken:
    secretKeyRef:
      name: github-secret
      key: accessToken
  secretToken:
    secretKeyRef:
      name: github-secret
      key: secretToken
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1beta1
      kind: KafkaChannel
      name: github-events
