apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: slack-sink
  annotations:
    kafka.eventing.knative.dev/delivery.order: ordered
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    name: github-events
  delivery:
    backoffDelay: PT1S
    backoffPolicy: linear
    retry: 5
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: slack-dls
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: slack-channel
